"""第一波 MVP 共享配置常量。"""

from __future__ import annotations

LANE_WIDTH_M = 3.2
CONTROL_ZONE_LENGTH_M = 600.0

RAMP_APPROACH_SUBZONE_M = (0, 50)
LEGAL_MERGE_ZONE_M = (50, 290)
EMERGENCY_TAIL_M = (290, 300)

ROLLOUT_TICK_S = 0.1
PLANNING_TICK_S = 0.1
GATE_SAMPLING_DT_S = 0.1
POST_MERGE_GUARD_S = 1.0
EPSILON_T_S = 0.05

A_MAX_MPS2 = 2.6
B_SAFE_MPS2 = 4.5
FAIL_SAFE_BRAKE_MPS2 = 4.5
COMFORTABLE_BRAKE_MPS2 = 2.0

MIN_GAP_M = 2.5
TIME_HEADWAY_S = 1.0
H_PR_S = 1.5
H_RF_S = 2.0

FIXED_ANCHOR_M = 170
LANE_CHANGE_DURATION_S = 3.0

MAINLINE_VMAX_MPS = 25.0
RAMP_VMAX_MPS = 16.7

__all__ = [
    "A_MAX_MPS2",
    "B_SAFE_MPS2",
    "COMFORTABLE_BRAKE_MPS2",
    "CONTROL_ZONE_LENGTH_M",
    "EMERGENCY_TAIL_M",
    "EPSILON_T_S",
    "FAIL_SAFE_BRAKE_MPS2",
    "FIXED_ANCHOR_M",
    "GATE_SAMPLING_DT_S",
    "H_PR_S",
    "H_RF_S",
    "LANE_CHANGE_DURATION_S",
    "LANE_WIDTH_M",
    "LEGAL_MERGE_ZONE_M",
    "MAINLINE_VMAX_MPS",
    "MIN_GAP_M",
    "PLANNING_TICK_S",
    "POST_MERGE_GUARD_S",
    "RAMP_APPROACH_SUBZONE_M",
    "RAMP_VMAX_MPS",
    "ROLLOUT_TICK_S",
    "TIME_HEADWAY_S",
]
