from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(slots=True)
class VehicleObs:
    veh_id: str
    stream: str
    road_id: str
    lane_id: str
    lane_pos_m: float
    speed_mps: float
    accel_mps2: float
    d_to_merge_m: float


@dataclass(slots=True)
class WorldState:
    sim_time_s: float
    active_vehicle_ids: set[str] = field(default_factory=set)
    control_zone: dict[str, VehicleObs] = field(default_factory=dict)
    entered_control: set[str] = field(default_factory=set)
    crossed_merge: set[str] = field(default_factory=set)
    entry_info: dict[str, dict[str, float | str]] = field(default_factory=dict)


@dataclass(slots=True)
class Plan:
    plan_time_s: float
    policy_name: str
    order: list[str] = field(default_factory=list)
    target_cross_time_s: dict[str, float] = field(default_factory=dict)
    eta_s: dict[str, float] = field(default_factory=dict)
    scheduler_fallback: bool = False


@dataclass(slots=True)
class MergeContract:
    """Zone B -> Zone C contract for a single ramp CAV merge action.

    Generated by the hierarchical scheduler from passing_order.
    Consumed by MergePointManager for targeted gap evaluation.
    """
    vehicle_id: str
    sequence_rank: int
    target_predecessor_id: str | None
    target_follower_id: str | None
    merge_window_start_s: float
    merge_window_end_s: float
    expected_merge_time_s: float
    desired_merge_speed_mps: float | None = None
    merge_phase: str = 'ALIGNING'
    fallback_allowed: bool = False


@dataclass(slots=True)
class ControlCommand:
    set_speed_mps: dict[str, float] = field(default_factory=dict)
    release_ids: set[str] = field(default_factory=set)
    # Deprecated: per-vehicle speed mode overrides are now handled by
    # TakeoverConfig (ramp.runtime.takeover).  Retained for backward
    # compatibility; policies should NOT populate these fields.
    takeover_speed_mode_by_id: dict[str, int] = field(default_factory=dict)
    restore_speed_mode_ids: set[str] = field(default_factory=set)
    lane_change_targets: dict[str, tuple[int, float]] = field(default_factory=dict)
    lane_change_mode_overrides: dict[str, int] = field(default_factory=dict)

